/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Product;
import customcontrols.GridViewPanel;
import customcontrols.Panel;
import customcontrols.TableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BoxLayout;


/**
 *
 * @author Vidhya Mohan
 */
public class BrowseProduct extends Panel {

    /**
     * Creates new form BrowseProduct
     */
    public BrowseProduct() {
        this.setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));        
        GridViewPanel grd = new GridViewPanel();
        grd.getGridView().getTableHeader().setBackground(Color.red);
        this.add(grd);
    }
    
    public void initialize() {
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
