/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Product;

import Helper.UIHelper;
import com.ims.dataAccess.tables.pojos.Product;

import com.ims.dataAccess.tables.pojos.Productcategory;
import customcontrols.Button;
import customcontrols.GridBagLayoutPanel;
import customcontrols.GridViewPanel;
import customcontrols.Label;
import customcontrols.LabelCombobox;
import customcontrols.LabelTextFieldInline;
import customcontrols.Panel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BoxLayout;
import repository.ProductCatgoryRepository;
import repository.test;



public class ProductFilterPanel extends Panel {

private Panel filterBox;
private Panel gridBox;

    public ProductFilterPanel() {
        initComponents();
        initialize();       
        //this.setMinimumSize(new Dimension(1200,150));
        this.setMaximumSize(new Dimension(skin.frameDimension.width,150));
        filterBox.setPreferredSize(new Dimension(700,150));         
          
    }
    
    private void initialize() {
        
      
        
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        filterBox = new Panel();       
       
        filterBox.setPreferredSize(new Dimension(700,10));  
        
        LabelTextFieldInline nameTextField = new LabelTextFieldInline("Name:", 350, 40);
       
        LabelTextFieldInline productIdField = new LabelTextFieldInline("ID:",  250, 70);
       
        LabelCombobox cmb = new LabelCombobox("Category:", 350, new String[]{"cat 1"});        
        GridBagLayoutPanel gbPanel = new GridBagLayoutPanel(2, 12, new Insets(20, 10, 0, 0));       
        
     
        
       gbPanel.addControl(this.uiHelper.getEmptyPanel(700, 10), GridBagLayoutPanel.Fill.nextLine); 
       gbPanel.addControl(new Label("Product Search: "), GridBagLayoutPanel.Fill.nextLine); 
       gbPanel.addControl(productIdField, GridBagLayoutPanel.Position.inline);
       gbPanel.addControl(nameTextField, GridBagLayoutPanel.Position.inline);
       gbPanel.addControl(cmb, GridBagLayoutPanel.Position.inline);
       gbPanel.addControlWithPosition(new Button("Search"), 2);        
       gbPanel.addControl(this.uiHelper.getEmptyPanel(700, 10),  GridBagLayoutPanel.Fill.nextLine);
       this.add(gbPanel);
       
       GridViewPanel grd = new GridViewPanel();
       grd.setBackground(Color.red);
        
//        gridBox = new Panel();
//        gridBox.setLayout(new GridBagLayout());
//        GridBagConstraints gc = new GridBagConstraints();     
//       // gc.fill = GridBagConstraints.HORIZONTAL;
//       // gc.ipadx = 2;
//        gc.gridx = 0;
//        gc.gridy = 0;
//        gc.anchor = GridBagConstraints.NORTHWEST;
//        gc.weightx = 0.1;
//        gc.weighty = 0;
//        gc.insets = new Insets(20, 0, 0, 0);
//       
//        gridBox.add(cmb, gc);
//        
//        gc.weightx = 0.1;
//        gc.weighty = 0;
//        gc.gridx = 1;
//        gc.gridy = 0;        
//        gridBox.add(cmb2, gc);
//        
//        gc.weightx = 0.1;
//        gc.weighty = 0;
//        gc.gridx = 2;
//        gc.gridy = 0;
//        
//        gridBox.add(nameTextField2, gc);
//        
//        
//        gc.weightx = 0.1;
//        gc.weighty = 0.1;
//        gc.gridx = 0;
//        gc.gridy = 1;       
//        
//        gridBox.add(nameTextField, gc);
//        
//        gc.weightx = 0.1;
//        gc.weighty = 0.1;
//        gc.gridx = 1;
//        gc.gridy = 1;      
//        gc.insets = new Insets(30, 90, 50, 0);
//        gc.fill = GridBagConstraints.HORIZONTAL;
//        gc.gridwidth = 1;
//        javax.swing.JPanel filler = new javax.swing.JPanel();
//        filler.setBackground(Color.red);
//        gridBox.add(filler, gc);
//        
//        
//        gc = new GridBagConstraints(); 
//        gc.weightx = 1;
//        gc.weighty = 0.1;
//        gc.gridx = 2;
//        gc.gridy = 1;      
//        gc.insets = new Insets(30, 60, 50, 0);
//        gc.fill = GridBagConstraints.HORIZONTAL;
//        gc.gridwidth = 1;
//        javax.swing.JPanel filler2 = new javax.swing.JPanel();
//        filler2.setBackground(Color.BLUE);
//        gridBox.add(filler2, gc);
//       
        
        
      //  this.add(filterBox);
      //  this.add(gridBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
