/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Product;

import Presentation.Common.BaseNavigationFrame;
import customcontrols.GridViewPanel;
import customcontrols.Label;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Vidhya Mohan
 */
public class ProductNavigation extends BaseNavigationFrame {

    private JTabbedPane tPane;
    private JPanel browse;
    private JPanel detail;
    /**
     * Creates new form ProductNavigation
     */
    public ProductNavigation() {
        super();
        initComponents();
        this.setBackground(this.skin.frameBackgroundColor);       
        this.setSize(this.skin.frameDimension);
        int width = skin.frameDimension.width;   
        super.setPanes();
        super.setNavigation();
        initialize();
    }
    
    public void initialize() {
        centerPane.setLayout(new BoxLayout(centerPane, BoxLayout.PAGE_AXIS));
        browse = new JPanel();
        browse.setLayout(new BoxLayout(browse, BoxLayout.PAGE_AXIS));
        detail = new JPanel();
        detail.setLayout(new BoxLayout(detail, BoxLayout.PAGE_AXIS));

        
        browse.add(new ProductFilterPanel());
        browse.add(new GridViewPanel());        
        
        tPane = new JTabbedPane();       
        tPane.addTab("Browse", browse);
        tPane.addTab("Detail", detail);       

        centerPane.add(tPane);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
