/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Product;
import Enums.NavigationAction;
import EventObject.TabChangeEventObj;
import Presentation.Common.TabNavigationPanel;
import com.ims.dataAccess.tables.pojos.Product;
import customcontrols.Button;
import customcontrols.GridCellRenderer;
import customcontrols.GridViewPanel;
import customcontrols.Panel;
import customcontrols.TableModel;
import domainModels.ProductModel;
import interfaces.TabChangeRequestHandler;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import net.miginfocom.swing.MigLayout;
import repository.ProductRepository;


/**
 *
 * @author Vidhya Mohan
 */
public class BrowseProduct extends TabNavigationPanel {

    /**
     * Creates new form BrowseProduct
     */
    GridViewPanel<ProductModel> grd;
    public BrowseProduct() {
        super();
        this.setLayout(new MigLayout());     
        //this.setLayout(new MigLayout());
        initializeBrowseProduct();
        this.add(grd, "span, grow, push");
        tabChangeHandlers = new ArrayList<TabChangeRequestHandler>();
    }
    
    public void initializeBrowseProduct() {
       grd = new GridViewPanel<ProductModel>();       
       loadGrid();
       grd.addDoubleClickHandler(e -> gridViewRowDoubleClicked((ProductModel) e));
       grd.addClickHandler(e -> gridViewClicked((ProductModel)e));
    }    
    
    public void loadGrid(List<ProductModel> productLists) {
       
        HashMap<String, String> columnsKeyVal = new LinkedHashMap<String, String>();    
   
        columnsKeyVal.put("productId", "Product Id");
        columnsKeyVal.put("name", "Product Name");
        columnsKeyVal.put("availableStock", "Available Stock");
        columnsKeyVal.put("productDescription", "Product Description");
        columnsKeyVal.put("price", "Price");
        columnsKeyVal.put("category-categoryName", "Category");
        columnsKeyVal.put("brand-brandName", "Brand Name");
        
       TableModel<ProductModel> tblModel = new TableModel<ProductModel>(new ArrayList(productLists), columnsKeyVal);
       grd.setModel(tblModel);
       grd.addGridButtonClickHandler(e -> gridButtonClicked(e));
    }
    
    public void loadGrid() {
        ArrayList<ProductModel> productLists = new ArrayList<ProductModel>();          
        
        ProductRepository repo = new ProductRepository();
        productLists = repo.getAll();

        loadGrid(productLists);
       //TableCellRenderer tableRenderer = grd.getGridView().getDefaultRenderer(Button.class);
       
       //grd.getGridView().setDefaultRenderer(Button.class, new GridCellRenderer(tableRenderer));
       //grd.getGridView().getColumn("Add To Order").setCellRenderer(new GridCellRenderer(tableRenderer, Button.class));
       
       
    }   
    
    public void gridViewClicked(ProductModel model) {
        this.fireDataNavigationChanged(model);
    }

    public void gridViewRowDoubleClicked(ProductModel model) {
       this.fireTabChangeRequest(new TabChangeEventObj(1, model, NavigationAction.Update));
    }
    
    public void gridButtonClicked(ProductModel model) {
        int h = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
