/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Product;

import Enums.NavigationAction;
import EventObject.TabChangeEventObj;
import Presentation.Common.BaseNavigationFrame;
import Presentation.Common.TabNavigationFrame;
import customcontrols.GridViewPanel;
import customcontrols.Label;
import customcontrols.Panel;
import domainModels.ProductModel;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Vidhya Mohan
 */
public class ProductNavigation extends TabNavigationFrame {
    
    ProductDetail productDetail;
    BrowseProduct browseProduct;

    /**
     * Creates new form ProductNavigation
     */
    public ProductNavigation() {
        super();    
        this.useMigLayout();
        initializeProductNavigation();
    }
    
    public void initializeProductNavigation() {    

        productDetail = new ProductDetail();
        browseProduct = new BrowseProduct();
        
        pnlBrowse.add(new ProductFilterPanel(), "span, growx, pushx");
        pnlBrowse.add(browseProduct, "span, growx, pushx");   
        pnlDetail.add(productDetail, "span, growx, pushx");
        
        browseProduct.addChangeTabRequest(e -> this.changeTab(e));
        productDetail.addChangeTabRequest(e -> this.changeTab(e));
        browseProduct.addDataNavigationChanged(e -> this.dataNavigationChanged((ProductModel)e));
        
        actionBar.setActionBarActions(NavigationAction.Browse);
    }   
    
    protected void dataNavigationChanged(ProductModel model) {
        productDetail.loadProduct(model);
    }

    @Override
    protected void changeTab(TabChangeEventObj eventObj) {         
        if (eventObj.tabIndex == 1)
        {
            if (eventObj.navAction == NavigationAction.Update) 
            {
              productDetail.loadProduct((ProductModel) eventObj.model);
            }
            else {
                productDetail.setDefaultValues();
            }
            tabControl.setSelectedIndex(eventObj.tabIndex);
            actionBar.setActionBarActions(eventObj.navAction);
        }
       else 
        if (eventObj.tabIndex == 0)
        {
            tabControl.setSelectedIndex(eventObj.tabIndex);
            browseProduct.loadGrid();
            actionBar.setActionBarActions(eventObj.navAction);
        }
    }
    
    @Override
    protected void TabChangeListener(ChangeEvent e){
        int selectedTab = tabControl.getSelectedIndex(); 
        
        if(selectedTab > 0) {
            if (selectedTab == 2) {
                
            }
        }
    }
    
    @Override
    protected void save() {
        productDetail.saveProduct();
    }
    
    @Override
    protected void add() {
        this.changeTab(new TabChangeEventObj(1, null, NavigationAction.Create));
    }
    
    @Override
    protected void delete() {
        productDetail.deleteProduct();
    }
    
    @Override 
    protected void update() {
        productDetail.updateProduct();
    }
    
    @Override 
    protected void cancel() {
        this.changeTab(new TabChangeEventObj(0, null, NavigationAction.Browse));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
