/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Product;

import Helper.UIHelper;
import com.ims.dataAccess.tables.pojos.Productcategory;



import customcontrols.Button;

import customcontrols.LabelCombobox;
import customcontrols.LabelTextFieldInline;
import customcontrols.Panel;
import domainModels.ProductCategoryModel;
import java.util.ArrayList;



import net.miginfocom.swing.MigLayout;
import repository.ProductCategoryRepository;

public class ProductFilterPanel extends Panel {

private Panel filterBox;
private Panel gridBox;

    public ProductFilterPanel() {
        initComponents();
        initializeProductFilterPanel(); 
          
    }
    
    private void initializeProductFilterPanel() {       
        
       
        this.setLayout(new MigLayout());
        filterBox = new Panel();         
        filterBox.setLayout(new MigLayout());      
    
        
        LabelTextFieldInline nameTextField = new LabelTextFieldInline("Name:", 250, 20);
       
        LabelTextFieldInline productIdField = new LabelTextFieldInline("ID:",  190, 20);
       
        ArrayList<String> categoryNames =  new ProductCategoryRepository().getAllCategoryNames();
        String[] items = new String[categoryNames.size()];
        LabelCombobox cmb = new LabelCombobox("Category:", 250, categoryNames.toArray(items));        
     
        
        filterBox.add(productIdField, "gapx 20, growx, pushx");
        filterBox.add(nameTextField, "gapx 20, growx, pushx");
        filterBox.add(cmb, "wrap, gapx 20, growx, pushx");
        filterBox.add(new Button("Search"), "skip 2, align trailing, gapy 40");       
     

       this.add(filterBox, "span, pushx, grow, gapright 60");     

    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
