/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customerorder implements Serializable {

    private static final long serialVersionUID = 1014062602;

    private Integer customerorderid;
    private Date    date;
    private String  orderdescription;
    private Integer customerid;

    public Customerorder() {}

    public Customerorder(Customerorder value) {
        this.customerorderid = value.customerorderid;
        this.date = value.date;
        this.orderdescription = value.orderdescription;
        this.customerid = value.customerid;
    }

    public Customerorder(
        Integer customerorderid,
        Date    date,
        String  orderdescription,
        Integer customerid
    ) {
        this.customerorderid = customerorderid;
        this.date = date;
        this.orderdescription = orderdescription;
        this.customerid = customerid;
    }

    public Integer getCustomerorderid() {
        return this.customerorderid;
    }

    public void setCustomerorderid(Integer customerorderid) {
        this.customerorderid = customerorderid;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getOrderdescription() {
        return this.orderdescription;
    }

    public void setOrderdescription(String orderdescription) {
        this.orderdescription = orderdescription;
    }

    public Integer getCustomerid() {
        return this.customerid;
    }

    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customerorder (");

        sb.append(customerorderid);
        sb.append(", ").append(date);
        sb.append(", ").append(orderdescription);
        sb.append(", ").append(customerid);

        sb.append(")");
        return sb.toString();
    }
}
