/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customerorderdetail implements Serializable {

    private static final long serialVersionUID = -1432737926;

    private Integer customerorderdetailid;
    private Integer productid;
    private Integer quantity;
    private Integer customerorderid;
    private String  orderdetailnotes;

    public Customerorderdetail() {}

    public Customerorderdetail(Customerorderdetail value) {
        this.customerorderdetailid = value.customerorderdetailid;
        this.productid = value.productid;
        this.quantity = value.quantity;
        this.customerorderid = value.customerorderid;
        this.orderdetailnotes = value.orderdetailnotes;
    }

    public Customerorderdetail(
        Integer customerorderdetailid,
        Integer productid,
        Integer quantity,
        Integer customerorderid,
        String  orderdetailnotes
    ) {
        this.customerorderdetailid = customerorderdetailid;
        this.productid = productid;
        this.quantity = quantity;
        this.customerorderid = customerorderid;
        this.orderdetailnotes = orderdetailnotes;
    }

    public Integer getCustomerorderdetailid() {
        return this.customerorderdetailid;
    }

    public void setCustomerorderdetailid(Integer customerorderdetailid) {
        this.customerorderdetailid = customerorderdetailid;
    }

    public Integer getProductid() {
        return this.productid;
    }

    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getCustomerorderid() {
        return this.customerorderid;
    }

    public void setCustomerorderid(Integer customerorderid) {
        this.customerorderid = customerorderid;
    }

    public String getOrderdetailnotes() {
        return this.orderdetailnotes;
    }

    public void setOrderdetailnotes(String orderdetailnotes) {
        this.orderdetailnotes = orderdetailnotes;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customerorderdetail (");

        sb.append(customerorderdetailid);
        sb.append(", ").append(productid);
        sb.append(", ").append(quantity);
        sb.append(", ").append(customerorderid);
        sb.append(", ").append(orderdetailnotes);

        sb.append(")");
        return sb.toString();
    }
}
