/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 1861568333;

    private Integer customerid;
    private Integer userid;

    public Customer() {}

    public Customer(Customer value) {
        this.customerid = value.customerid;
        this.userid = value.userid;
    }

    public Customer(
        Integer customerid,
        Integer userid
    ) {
        this.customerid = customerid;
        this.userid = userid;
    }

    public Integer getCustomerid() {
        return this.customerid;
    }

    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(customerid);
        sb.append(", ").append(userid);

        sb.append(")");
        return sb.toString();
    }
}
