/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dealer implements Serializable {

    private static final long serialVersionUID = -726907385;

    private Integer dealerid;
    private Integer userid;
    private String  companyname;
    private String  dealerdescription;

    public Dealer() {}

    public Dealer(Dealer value) {
        this.dealerid = value.dealerid;
        this.userid = value.userid;
        this.companyname = value.companyname;
        this.dealerdescription = value.dealerdescription;
    }

    public Dealer(
        Integer dealerid,
        Integer userid,
        String  companyname,
        String  dealerdescription
    ) {
        this.dealerid = dealerid;
        this.userid = userid;
        this.companyname = companyname;
        this.dealerdescription = dealerdescription;
    }

    public Integer getDealerid() {
        return this.dealerid;
    }

    public void setDealerid(Integer dealerid) {
        this.dealerid = dealerid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    public String getDealerdescription() {
        return this.dealerdescription;
    }

    public void setDealerdescription(String dealerdescription) {
        this.dealerdescription = dealerdescription;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dealer (");

        sb.append(dealerid);
        sb.append(", ").append(userid);
        sb.append(", ").append(companyname);
        sb.append(", ").append(dealerdescription);

        sb.append(")");
        return sb.toString();
    }
}
