/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = -161587702;

    private Integer productid;
    private String  name;
    private Integer availablestock;
    private String  productdescription;
    private Long    price;
    private byte[]  image;
    private Integer categoryid;
    private Integer brandid;
    private Integer dealerid;

    public Product() {}

    public Product(Product value) {
        this.productid = value.productid;
        this.name = value.name;
        this.availablestock = value.availablestock;
        this.productdescription = value.productdescription;
        this.price = value.price;
        this.image = value.image;
        this.categoryid = value.categoryid;
        this.brandid = value.brandid;
        this.dealerid = value.dealerid;
    }

    public Product(
        Integer productid,
        String  name,
        Integer availablestock,
        String  productdescription,
        Long    price,
        byte[]  image,
        Integer categoryid,
        Integer brandid,
        Integer dealerid
    ) {
        this.productid = productid;
        this.name = name;
        this.availablestock = availablestock;
        this.productdescription = productdescription;
        this.price = price;
        this.image = image;
        this.categoryid = categoryid;
        this.brandid = brandid;
        this.dealerid = dealerid;
    }

    public Integer getProductid() {
        return this.productid;
    }

    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAvailablestock() {
        return this.availablestock;
    }

    public void setAvailablestock(Integer availablestock) {
        this.availablestock = availablestock;
    }

    public String getProductdescription() {
        return this.productdescription;
    }

    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    public Long getPrice() {
        return this.price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte... image) {
        this.image = image;
    }

    public Integer getCategoryid() {
        return this.categoryid;
    }

    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    public Integer getBrandid() {
        return this.brandid;
    }

    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    public Integer getDealerid() {
        return this.dealerid;
    }

    public void setDealerid(Integer dealerid) {
        this.dealerid = dealerid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(productid);
        sb.append(", ").append(name);
        sb.append(", ").append(availablestock);
        sb.append(", ").append(productdescription);
        sb.append(", ").append(price);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(categoryid);
        sb.append(", ").append(brandid);
        sb.append(", ").append(dealerid);

        sb.append(")");
        return sb.toString();
    }
}
