/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Productcategory implements Serializable {

    private static final long serialVersionUID = -1522003216;

    private Integer categoryid;
    private String  categoryname;
    private String  categorydescription;

    public Productcategory() {}

    public Productcategory(Productcategory value) {
        this.categoryid = value.categoryid;
        this.categoryname = value.categoryname;
        this.categorydescription = value.categorydescription;
    }

    public Productcategory(
        Integer categoryid,
        String  categoryname,
        String  categorydescription
    ) {
        this.categoryid = categoryid;
        this.categoryname = categoryname;
        this.categorydescription = categorydescription;
    }

    public Integer getCategoryid() {
        return this.categoryid;
    }

    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    public String getCategoryname() {
        return this.categoryname;
    }

    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    public String getCategorydescription() {
        return this.categorydescription;
    }

    public void setCategorydescription(String categorydescription) {
        this.categorydescription = categorydescription;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Productcategory (");

        sb.append(categoryid);
        sb.append(", ").append(categoryname);
        sb.append(", ").append(categorydescription);

        sb.append(")");
        return sb.toString();
    }
}
