/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purchase implements Serializable {

    private static final long serialVersionUID = -1204754648;

    private Integer purchaseid;
    private String  purchasename;
    private String  purchasedescription;
    private Date    purchasedate;
    private Date    deliverydate;
    private String  shipmenttype;

    public Purchase() {}

    public Purchase(Purchase value) {
        this.purchaseid = value.purchaseid;
        this.purchasename = value.purchasename;
        this.purchasedescription = value.purchasedescription;
        this.purchasedate = value.purchasedate;
        this.deliverydate = value.deliverydate;
        this.shipmenttype = value.shipmenttype;
    }

    public Purchase(
        Integer purchaseid,
        String  purchasename,
        String  purchasedescription,
        Date    purchasedate,
        Date    deliverydate,
        String  shipmenttype
    ) {
        this.purchaseid = purchaseid;
        this.purchasename = purchasename;
        this.purchasedescription = purchasedescription;
        this.purchasedate = purchasedate;
        this.deliverydate = deliverydate;
        this.shipmenttype = shipmenttype;
    }

    public Integer getPurchaseid() {
        return this.purchaseid;
    }

    public void setPurchaseid(Integer purchaseid) {
        this.purchaseid = purchaseid;
    }

    public String getPurchasename() {
        return this.purchasename;
    }

    public void setPurchasename(String purchasename) {
        this.purchasename = purchasename;
    }

    public String getPurchasedescription() {
        return this.purchasedescription;
    }

    public void setPurchasedescription(String purchasedescription) {
        this.purchasedescription = purchasedescription;
    }

    public Date getPurchasedate() {
        return this.purchasedate;
    }

    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    public Date getDeliverydate() {
        return this.deliverydate;
    }

    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }

    public String getShipmenttype() {
        return this.shipmenttype;
    }

    public void setShipmenttype(String shipmenttype) {
        this.shipmenttype = shipmenttype;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Purchase (");

        sb.append(purchaseid);
        sb.append(", ").append(purchasename);
        sb.append(", ").append(purchasedescription);
        sb.append(", ").append(purchasedate);
        sb.append(", ").append(deliverydate);
        sb.append(", ").append(shipmenttype);

        sb.append(")");
        return sb.toString();
    }
}
