/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -717005067;

    private Integer userid;
    private Integer usertypeid;
    private String  firstname;
    private String  lastname;
    private Integer age;
    private String  gender;
    private String  email;
    private String  mobilenumber;
    private String  username;
    private String  password;
    private Integer houseno;
    private String  streetname;
    private String  suburb;
    private String  city;

    public User() {}

    public User(User value) {
        this.userid = value.userid;
        this.usertypeid = value.usertypeid;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.age = value.age;
        this.gender = value.gender;
        this.email = value.email;
        this.mobilenumber = value.mobilenumber;
        this.username = value.username;
        this.password = value.password;
        this.houseno = value.houseno;
        this.streetname = value.streetname;
        this.suburb = value.suburb;
        this.city = value.city;
    }

    public User(
        Integer userid,
        Integer usertypeid,
        String  firstname,
        String  lastname,
        Integer age,
        String  gender,
        String  email,
        String  mobilenumber,
        String  username,
        String  password,
        Integer houseno,
        String  streetname,
        String  suburb,
        String  city
    ) {
        this.userid = userid;
        this.usertypeid = usertypeid;
        this.firstname = firstname;
        this.lastname = lastname;
        this.age = age;
        this.gender = gender;
        this.email = email;
        this.mobilenumber = mobilenumber;
        this.username = username;
        this.password = password;
        this.houseno = houseno;
        this.streetname = streetname;
        this.suburb = suburb;
        this.city = city;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getUsertypeid() {
        return this.usertypeid;
    }

    public void setUsertypeid(Integer usertypeid) {
        this.usertypeid = usertypeid;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobilenumber() {
        return this.mobilenumber;
    }

    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getHouseno() {
        return this.houseno;
    }

    public void setHouseno(Integer houseno) {
        this.houseno = houseno;
    }

    public String getStreetname() {
        return this.streetname;
    }

    public void setStreetname(String streetname) {
        this.streetname = streetname;
    }

    public String getSuburb() {
        return this.suburb;
    }

    public void setSuburb(String suburb) {
        this.suburb = suburb;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userid);
        sb.append(", ").append(usertypeid);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(age);
        sb.append(", ").append(gender);
        sb.append(", ").append(email);
        sb.append(", ").append(mobilenumber);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(houseno);
        sb.append(", ").append(streetname);
        sb.append(", ").append(suburb);
        sb.append(", ").append(city);

        sb.append(")");
        return sb.toString();
    }
}
