/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usertype implements Serializable {

    private static final long serialVersionUID = -1415700151;

    private Integer usertypeid;
    private String  usertypename;
    private String  usertypedescription;

    public Usertype() {}

    public Usertype(Usertype value) {
        this.usertypeid = value.usertypeid;
        this.usertypename = value.usertypename;
        this.usertypedescription = value.usertypedescription;
    }

    public Usertype(
        Integer usertypeid,
        String  usertypename,
        String  usertypedescription
    ) {
        this.usertypeid = usertypeid;
        this.usertypename = usertypename;
        this.usertypedescription = usertypedescription;
    }

    public Integer getUsertypeid() {
        return this.usertypeid;
    }

    public void setUsertypeid(Integer usertypeid) {
        this.usertypeid = usertypeid;
    }

    public String getUsertypename() {
        return this.usertypename;
    }

    public void setUsertypename(String usertypename) {
        this.usertypename = usertypename;
    }

    public String getUsertypedescription() {
        return this.usertypedescription;
    }

    public void setUsertypedescription(String usertypedescription) {
        this.usertypedescription = usertypedescription;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usertype (");

        sb.append(usertypeid);
        sb.append(", ").append(usertypename);
        sb.append(", ").append(usertypedescription);

        sb.append(")");
        return sb.toString();
    }
}
