/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customcontrols;

import Skin.Skin;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author Vidhya Mohan
 */
public class CatalogPanel extends javax.swing.JPanel {

    Skin skin = new Skin();
    /**
     * Creates new form CatalogPanel
     */
    public CatalogPanel() {
        initComponents();
    }
    
     public CatalogPanel(String titleName, ImageIcon catalogImageIcon, Dimension size) {
        initComponents();
        this.lblTitle.setText(titleName);
        this.lblTitle.setForeground(skin.milkWhiteColor);
        this.lblTitle.setAlignmentX(SwingConstants.CENTER);
        this.lblCatalogIcon.setIcon(catalogImageIcon);
        this.lblTitle.setFont(skin.fontBold28);
        this.lblCatalogIcon.setText("");
        this.setPreferredSize(size);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCatalogIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        lblCatalogIcon.setText("jLabel1");

        lblTitle.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCatalogIcon)
                    .addComponent(lblTitle))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblCatalogIcon)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCatalogIcon;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
