/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess;


import com.ims.dataAccess.tables.Brand;
import com.ims.dataAccess.tables.Customer;
import com.ims.dataAccess.tables.Customerorder;
import com.ims.dataAccess.tables.Customerorderdetail;
import com.ims.dataAccess.tables.Dealer;
import com.ims.dataAccess.tables.Product;
import com.ims.dataAccess.tables.Productcategory;
import com.ims.dataAccess.tables.Purchase;
import com.ims.dataAccess.tables.Purchasedetail;
import com.ims.dataAccess.tables.User;
import com.ims.dataAccess.tables.Usertype;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>inventorymanagement</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BRAND_BRAND_NAME_UNIQUE = Indexes0.BRAND_BRAND_NAME_UNIQUE;
    public static final Index BRAND_PRIMARY = Indexes0.BRAND_PRIMARY;
    public static final Index CUSTOMER_CUSTOMER_USERID_FK = Indexes0.CUSTOMER_CUSTOMER_USERID_FK;
    public static final Index CUSTOMER_PRIMARY = Indexes0.CUSTOMER_PRIMARY;
    public static final Index CUSTOMERORDER_ORDER_CUSTOMERID_FK = Indexes0.CUSTOMERORDER_ORDER_CUSTOMERID_FK;
    public static final Index CUSTOMERORDER_PRIMARY = Indexes0.CUSTOMERORDER_PRIMARY;
    public static final Index CUSTOMERORDERDETAIL_CUSTOMERORDERDETAIL_CUSTOMERORDERID_FK = Indexes0.CUSTOMERORDERDETAIL_CUSTOMERORDERDETAIL_CUSTOMERORDERID_FK;
    public static final Index CUSTOMERORDERDETAIL_CUSTOMERORDERDETAIL_PRODUCTID_FK = Indexes0.CUSTOMERORDERDETAIL_CUSTOMERORDERDETAIL_PRODUCTID_FK;
    public static final Index CUSTOMERORDERDETAIL_PRIMARY = Indexes0.CUSTOMERORDERDETAIL_PRIMARY;
    public static final Index DEALER_DEALER_USERID_FK = Indexes0.DEALER_DEALER_USERID_FK;
    public static final Index DEALER_PRIMARY = Indexes0.DEALER_PRIMARY;
    public static final Index PRODUCT_PRIMARY = Indexes0.PRODUCT_PRIMARY;
    public static final Index PRODUCT_PRODUCT_BRANDID_FK = Indexes0.PRODUCT_PRODUCT_BRANDID_FK;
    public static final Index PRODUCT_PRODUCT_CATEGORYID_FK = Indexes0.PRODUCT_PRODUCT_CATEGORYID_FK;
    public static final Index PRODUCT_PRODUCT_DEALERID_FK = Indexes0.PRODUCT_PRODUCT_DEALERID_FK;
    public static final Index PRODUCTCATEGORY_PRIMARY = Indexes0.PRODUCTCATEGORY_PRIMARY;
    public static final Index PRODUCTCATEGORY_PRODUCTCATEGORY_NAME_UNIQUE = Indexes0.PRODUCTCATEGORY_PRODUCTCATEGORY_NAME_UNIQUE;
    public static final Index PURCHASE_PRIMARY = Indexes0.PURCHASE_PRIMARY;
    public static final Index PURCHASE_PURCHASE_PURCHASENAME_UNIQUE = Indexes0.PURCHASE_PURCHASE_PURCHASENAME_UNIQUE;
    public static final Index PURCHASEDETAIL_PRIMARY = Indexes0.PURCHASEDETAIL_PRIMARY;
    public static final Index PURCHASEDETAIL_PRODUCT_PRODUCTID_FK = Indexes0.PURCHASEDETAIL_PRODUCT_PRODUCTID_FK;
    public static final Index PURCHASEDETAIL_PURCHASEDETAIL_PURCHASEID_FK = Indexes0.PURCHASEDETAIL_PURCHASEDETAIL_PURCHASEID_FK;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_USER_USERTYPEID_FK = Indexes0.USER_USER_USERTYPEID_FK;
    public static final Index USERTYPE_PRIMARY = Indexes0.USERTYPE_PRIMARY;
    public static final Index USERTYPE_USERTYPE_NAME_UNIQUE = Indexes0.USERTYPE_USERTYPE_NAME_UNIQUE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BRAND_BRAND_NAME_UNIQUE = Internal.createIndex("brand_name_unique", Brand.BRAND, new OrderField[] { Brand.BRAND.BRANDNAME }, true);
        public static Index BRAND_PRIMARY = Internal.createIndex("PRIMARY", Brand.BRAND, new OrderField[] { Brand.BRAND.BRANDID }, true);
        public static Index CUSTOMER_CUSTOMER_USERID_FK = Internal.createIndex("customer_userId_fk", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.USERID }, false);
        public static Index CUSTOMER_PRIMARY = Internal.createIndex("PRIMARY", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.CUSTOMERID }, true);
        public static Index CUSTOMERORDER_ORDER_CUSTOMERID_FK = Internal.createIndex("order_customerId_fk", Customerorder.CUSTOMERORDER, new OrderField[] { Customerorder.CUSTOMERORDER.CUSTOMERID }, false);
        public static Index CUSTOMERORDER_PRIMARY = Internal.createIndex("PRIMARY", Customerorder.CUSTOMERORDER, new OrderField[] { Customerorder.CUSTOMERORDER.CUSTOMERORDERID }, true);
        public static Index CUSTOMERORDERDETAIL_CUSTOMERORDERDETAIL_CUSTOMERORDERID_FK = Internal.createIndex("customerOrderDetail_customerOrderId_fk", Customerorderdetail.CUSTOMERORDERDETAIL, new OrderField[] { Customerorderdetail.CUSTOMERORDERDETAIL.CUSTOMERORDERID }, false);
        public static Index CUSTOMERORDERDETAIL_CUSTOMERORDERDETAIL_PRODUCTID_FK = Internal.createIndex("customerOrderDetail_productId_fk", Customerorderdetail.CUSTOMERORDERDETAIL, new OrderField[] { Customerorderdetail.CUSTOMERORDERDETAIL.PRODUCTID }, false);
        public static Index CUSTOMERORDERDETAIL_PRIMARY = Internal.createIndex("PRIMARY", Customerorderdetail.CUSTOMERORDERDETAIL, new OrderField[] { Customerorderdetail.CUSTOMERORDERDETAIL.CUSTOMERORDERDETAILID }, true);
        public static Index DEALER_DEALER_USERID_FK = Internal.createIndex("dealer_userId_fk", Dealer.DEALER, new OrderField[] { Dealer.DEALER.USERID }, false);
        public static Index DEALER_PRIMARY = Internal.createIndex("PRIMARY", Dealer.DEALER, new OrderField[] { Dealer.DEALER.DEALERID }, true);
        public static Index PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Product.PRODUCT, new OrderField[] { Product.PRODUCT.PRODUCTID }, true);
        public static Index PRODUCT_PRODUCT_BRANDID_FK = Internal.createIndex("product_brandId_fk", Product.PRODUCT, new OrderField[] { Product.PRODUCT.BRANDID }, false);
        public static Index PRODUCT_PRODUCT_CATEGORYID_FK = Internal.createIndex("product_categoryId_fk", Product.PRODUCT, new OrderField[] { Product.PRODUCT.CATEGORYID }, false);
        public static Index PRODUCT_PRODUCT_DEALERID_FK = Internal.createIndex("product_dealerId_fk", Product.PRODUCT, new OrderField[] { Product.PRODUCT.DEALERID }, false);
        public static Index PRODUCTCATEGORY_PRIMARY = Internal.createIndex("PRIMARY", Productcategory.PRODUCTCATEGORY, new OrderField[] { Productcategory.PRODUCTCATEGORY.CATEGORYID }, true);
        public static Index PRODUCTCATEGORY_PRODUCTCATEGORY_NAME_UNIQUE = Internal.createIndex("productCategory_name_unique", Productcategory.PRODUCTCATEGORY, new OrderField[] { Productcategory.PRODUCTCATEGORY.CATEGORYNAME }, true);
        public static Index PURCHASE_PRIMARY = Internal.createIndex("PRIMARY", Purchase.PURCHASE, new OrderField[] { Purchase.PURCHASE.PURCHASEID }, true);
        public static Index PURCHASE_PURCHASE_PURCHASENAME_UNIQUE = Internal.createIndex("purchase_purchaseName_unique", Purchase.PURCHASE, new OrderField[] { Purchase.PURCHASE.PURCHASENAME }, true);
        public static Index PURCHASEDETAIL_PRIMARY = Internal.createIndex("PRIMARY", Purchasedetail.PURCHASEDETAIL, new OrderField[] { Purchasedetail.PURCHASEDETAIL.PURCHASEDETAILID }, true);
        public static Index PURCHASEDETAIL_PRODUCT_PRODUCTID_FK = Internal.createIndex("product_productId_fk", Purchasedetail.PURCHASEDETAIL, new OrderField[] { Purchasedetail.PURCHASEDETAIL.PRODUCTID }, false);
        public static Index PURCHASEDETAIL_PURCHASEDETAIL_PURCHASEID_FK = Internal.createIndex("purchaseDetail_purchaseId_fk", Purchasedetail.PURCHASEDETAIL, new OrderField[] { Purchasedetail.PURCHASEDETAIL.PURCHASEID }, false);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.USERID }, true);
        public static Index USER_USER_USERTYPEID_FK = Internal.createIndex("user_userTypeId_fk", User.USER, new OrderField[] { User.USER.USERTYPEID }, false);
        public static Index USERTYPE_PRIMARY = Internal.createIndex("PRIMARY", Usertype.USERTYPE, new OrderField[] { Usertype.USERTYPE.USERTYPEID }, true);
        public static Index USERTYPE_USERTYPE_NAME_UNIQUE = Internal.createIndex("userType_name_unique", Usertype.USERTYPE, new OrderField[] { Usertype.USERTYPE.USERTYPENAME }, true);
    }
}
