/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess;


import com.ims.dataAccess.tables.Brand;
import com.ims.dataAccess.tables.Customer;
import com.ims.dataAccess.tables.Customerorder;
import com.ims.dataAccess.tables.Customerorderdetail;
import com.ims.dataAccess.tables.Dealer;
import com.ims.dataAccess.tables.Product;
import com.ims.dataAccess.tables.Productcategory;
import com.ims.dataAccess.tables.Purchase;
import com.ims.dataAccess.tables.Purchasedetail;
import com.ims.dataAccess.tables.User;
import com.ims.dataAccess.tables.Usertype;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inventorymanagement extends SchemaImpl {

    private static final long serialVersionUID = 1069438772;

    /**
     * The reference instance of <code>inventorymanagement</code>
     */
    public static final Inventorymanagement INVENTORYMANAGEMENT = new Inventorymanagement();

    /**
     * The table <code>inventorymanagement.brand</code>.
     */
    public final Brand BRAND = com.ims.dataAccess.tables.Brand.BRAND;

    /**
     * The table <code>inventorymanagement.customer</code>.
     */
    public final Customer CUSTOMER = com.ims.dataAccess.tables.Customer.CUSTOMER;

    /**
     * The table <code>inventorymanagement.customerorder</code>.
     */
    public final Customerorder CUSTOMERORDER = com.ims.dataAccess.tables.Customerorder.CUSTOMERORDER;

    /**
     * The table <code>inventorymanagement.customerorderdetail</code>.
     */
    public final Customerorderdetail CUSTOMERORDERDETAIL = com.ims.dataAccess.tables.Customerorderdetail.CUSTOMERORDERDETAIL;

    /**
     * The table <code>inventorymanagement.dealer</code>.
     */
    public final Dealer DEALER = com.ims.dataAccess.tables.Dealer.DEALER;

    /**
     * The table <code>inventorymanagement.product</code>.
     */
    public final Product PRODUCT = com.ims.dataAccess.tables.Product.PRODUCT;

    /**
     * The table <code>inventorymanagement.productcategory</code>.
     */
    public final Productcategory PRODUCTCATEGORY = com.ims.dataAccess.tables.Productcategory.PRODUCTCATEGORY;

    /**
     * The table <code>inventorymanagement.purchase</code>.
     */
    public final Purchase PURCHASE = com.ims.dataAccess.tables.Purchase.PURCHASE;

    /**
     * The table <code>inventorymanagement.purchasedetail</code>.
     */
    public final Purchasedetail PURCHASEDETAIL = com.ims.dataAccess.tables.Purchasedetail.PURCHASEDETAIL;

    /**
     * The table <code>inventorymanagement.user</code>.
     */
    public final User USER = com.ims.dataAccess.tables.User.USER;

    /**
     * The table <code>inventorymanagement.usertype</code>.
     */
    public final Usertype USERTYPE = com.ims.dataAccess.tables.Usertype.USERTYPE;

    /**
     * No further instances allowed
     */
    private Inventorymanagement() {
        super("inventorymanagement", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Brand.BRAND,
            Customer.CUSTOMER,
            Customerorder.CUSTOMERORDER,
            Customerorderdetail.CUSTOMERORDERDETAIL,
            Dealer.DEALER,
            Product.PRODUCT,
            Productcategory.PRODUCTCATEGORY,
            Purchase.PURCHASE,
            Purchasedetail.PURCHASEDETAIL,
            User.USER,
            Usertype.USERTYPE);
    }
}
