/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess;


import com.ims.dataAccess.tables.Brand;
import com.ims.dataAccess.tables.Customer;
import com.ims.dataAccess.tables.Customerorder;
import com.ims.dataAccess.tables.Customerorderdetail;
import com.ims.dataAccess.tables.Dealer;
import com.ims.dataAccess.tables.Product;
import com.ims.dataAccess.tables.Productcategory;
import com.ims.dataAccess.tables.Purchase;
import com.ims.dataAccess.tables.Purchasedetail;
import com.ims.dataAccess.tables.User;
import com.ims.dataAccess.tables.Usertype;
import com.ims.dataAccess.tables.records.BrandRecord;
import com.ims.dataAccess.tables.records.CustomerRecord;
import com.ims.dataAccess.tables.records.CustomerorderRecord;
import com.ims.dataAccess.tables.records.CustomerorderdetailRecord;
import com.ims.dataAccess.tables.records.DealerRecord;
import com.ims.dataAccess.tables.records.ProductRecord;
import com.ims.dataAccess.tables.records.ProductcategoryRecord;
import com.ims.dataAccess.tables.records.PurchaseRecord;
import com.ims.dataAccess.tables.records.PurchasedetailRecord;
import com.ims.dataAccess.tables.records.UserRecord;
import com.ims.dataAccess.tables.records.UsertypeRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>inventorymanagement</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BrandRecord, Integer> IDENTITY_BRAND = Identities0.IDENTITY_BRAND;
    public static final Identity<CustomerRecord, Integer> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
    public static final Identity<CustomerorderRecord, Integer> IDENTITY_CUSTOMERORDER = Identities0.IDENTITY_CUSTOMERORDER;
    public static final Identity<CustomerorderdetailRecord, Integer> IDENTITY_CUSTOMERORDERDETAIL = Identities0.IDENTITY_CUSTOMERORDERDETAIL;
    public static final Identity<DealerRecord, Integer> IDENTITY_DEALER = Identities0.IDENTITY_DEALER;
    public static final Identity<ProductRecord, Integer> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;
    public static final Identity<ProductcategoryRecord, Integer> IDENTITY_PRODUCTCATEGORY = Identities0.IDENTITY_PRODUCTCATEGORY;
    public static final Identity<PurchaseRecord, Integer> IDENTITY_PURCHASE = Identities0.IDENTITY_PURCHASE;
    public static final Identity<PurchasedetailRecord, Integer> IDENTITY_PURCHASEDETAIL = Identities0.IDENTITY_PURCHASEDETAIL;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
    public static final Identity<UsertypeRecord, Integer> IDENTITY_USERTYPE = Identities0.IDENTITY_USERTYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BrandRecord> KEY_BRAND_PRIMARY = UniqueKeys0.KEY_BRAND_PRIMARY;
    public static final UniqueKey<BrandRecord> KEY_BRAND_BRAND_NAME_UNIQUE = UniqueKeys0.KEY_BRAND_BRAND_NAME_UNIQUE;
    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = UniqueKeys0.KEY_CUSTOMER_PRIMARY;
    public static final UniqueKey<CustomerorderRecord> KEY_CUSTOMERORDER_PRIMARY = UniqueKeys0.KEY_CUSTOMERORDER_PRIMARY;
    public static final UniqueKey<CustomerorderdetailRecord> KEY_CUSTOMERORDERDETAIL_PRIMARY = UniqueKeys0.KEY_CUSTOMERORDERDETAIL_PRIMARY;
    public static final UniqueKey<DealerRecord> KEY_DEALER_PRIMARY = UniqueKeys0.KEY_DEALER_PRIMARY;
    public static final UniqueKey<DealerRecord> KEY_DEALER_DEALER_COMPANY_UNIQUE = UniqueKeys0.KEY_DEALER_DEALER_COMPANY_UNIQUE;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<ProductcategoryRecord> KEY_PRODUCTCATEGORY_PRIMARY = UniqueKeys0.KEY_PRODUCTCATEGORY_PRIMARY;
    public static final UniqueKey<ProductcategoryRecord> KEY_PRODUCTCATEGORY_PRODUCTCATEGORY_NAME_UNIQUE = UniqueKeys0.KEY_PRODUCTCATEGORY_PRODUCTCATEGORY_NAME_UNIQUE;
    public static final UniqueKey<PurchaseRecord> KEY_PURCHASE_PRIMARY = UniqueKeys0.KEY_PURCHASE_PRIMARY;
    public static final UniqueKey<PurchaseRecord> KEY_PURCHASE_PURCHASE_PURCHASENAME_UNIQUE = UniqueKeys0.KEY_PURCHASE_PURCHASE_PURCHASENAME_UNIQUE;
    public static final UniqueKey<PurchasedetailRecord> KEY_PURCHASEDETAIL_PRIMARY = UniqueKeys0.KEY_PURCHASEDETAIL_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UsertypeRecord> KEY_USERTYPE_PRIMARY = UniqueKeys0.KEY_USERTYPE_PRIMARY;
    public static final UniqueKey<UsertypeRecord> KEY_USERTYPE_USERTYPE_NAME_UNIQUE = UniqueKeys0.KEY_USERTYPE_USERTYPE_NAME_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerRecord, UserRecord> CUSTOMER_USERID_FK = ForeignKeys0.CUSTOMER_USERID_FK;
    public static final ForeignKey<CustomerorderRecord, CustomerRecord> ORDER_CUSTOMERID_FK = ForeignKeys0.ORDER_CUSTOMERID_FK;
    public static final ForeignKey<CustomerorderdetailRecord, ProductRecord> CUSTOMERORDERDETAIL_PRODUCTID_FK = ForeignKeys0.CUSTOMERORDERDETAIL_PRODUCTID_FK;
    public static final ForeignKey<CustomerorderdetailRecord, CustomerorderRecord> CUSTOMERORDERDETAIL_CUSTOMERORDERID_FK = ForeignKeys0.CUSTOMERORDERDETAIL_CUSTOMERORDERID_FK;
    public static final ForeignKey<DealerRecord, UserRecord> DEALER_USERID_FK = ForeignKeys0.DEALER_USERID_FK;
    public static final ForeignKey<ProductRecord, ProductcategoryRecord> PRODUCT_CATEGORYID_FK = ForeignKeys0.PRODUCT_CATEGORYID_FK;
    public static final ForeignKey<ProductRecord, BrandRecord> PRODUCT_BRANDID_FK = ForeignKeys0.PRODUCT_BRANDID_FK;
    public static final ForeignKey<ProductRecord, DealerRecord> PRODUCT_DEALERID_FK = ForeignKeys0.PRODUCT_DEALERID_FK;
    public static final ForeignKey<PurchasedetailRecord, PurchaseRecord> PURCHASEDETAIL_PURCHASEID_FK = ForeignKeys0.PURCHASEDETAIL_PURCHASEID_FK;
    public static final ForeignKey<PurchasedetailRecord, ProductRecord> PRODUCT_PRODUCTID_FK = ForeignKeys0.PRODUCT_PRODUCTID_FK;
    public static final ForeignKey<UserRecord, UsertypeRecord> USER_USERTYPEID_FK = ForeignKeys0.USER_USERTYPEID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BrandRecord, Integer> IDENTITY_BRAND = Internal.createIdentity(Brand.BRAND, Brand.BRAND.BRANDID);
        public static Identity<CustomerRecord, Integer> IDENTITY_CUSTOMER = Internal.createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.CUSTOMERID);
        public static Identity<CustomerorderRecord, Integer> IDENTITY_CUSTOMERORDER = Internal.createIdentity(Customerorder.CUSTOMERORDER, Customerorder.CUSTOMERORDER.CUSTOMERORDERID);
        public static Identity<CustomerorderdetailRecord, Integer> IDENTITY_CUSTOMERORDERDETAIL = Internal.createIdentity(Customerorderdetail.CUSTOMERORDERDETAIL, Customerorderdetail.CUSTOMERORDERDETAIL.CUSTOMERORDERDETAILID);
        public static Identity<DealerRecord, Integer> IDENTITY_DEALER = Internal.createIdentity(Dealer.DEALER, Dealer.DEALER.DEALERID);
        public static Identity<ProductRecord, Integer> IDENTITY_PRODUCT = Internal.createIdentity(Product.PRODUCT, Product.PRODUCT.PRODUCTID);
        public static Identity<ProductcategoryRecord, Integer> IDENTITY_PRODUCTCATEGORY = Internal.createIdentity(Productcategory.PRODUCTCATEGORY, Productcategory.PRODUCTCATEGORY.CATEGORYID);
        public static Identity<PurchaseRecord, Integer> IDENTITY_PURCHASE = Internal.createIdentity(Purchase.PURCHASE, Purchase.PURCHASE.PURCHASEID);
        public static Identity<PurchasedetailRecord, Integer> IDENTITY_PURCHASEDETAIL = Internal.createIdentity(Purchasedetail.PURCHASEDETAIL, Purchasedetail.PURCHASEDETAIL.PURCHASEDETAILID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.USERID);
        public static Identity<UsertypeRecord, Integer> IDENTITY_USERTYPE = Internal.createIdentity(Usertype.USERTYPE, Usertype.USERTYPE.USERTYPEID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BrandRecord> KEY_BRAND_PRIMARY = Internal.createUniqueKey(Brand.BRAND, "KEY_brand_PRIMARY", Brand.BRAND.BRANDID);
        public static final UniqueKey<BrandRecord> KEY_BRAND_BRAND_NAME_UNIQUE = Internal.createUniqueKey(Brand.BRAND, "KEY_brand_brand_name_unique", Brand.BRAND.BRANDNAME);
        public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = Internal.createUniqueKey(Customer.CUSTOMER, "KEY_customer_PRIMARY", Customer.CUSTOMER.CUSTOMERID);
        public static final UniqueKey<CustomerorderRecord> KEY_CUSTOMERORDER_PRIMARY = Internal.createUniqueKey(Customerorder.CUSTOMERORDER, "KEY_customerorder_PRIMARY", Customerorder.CUSTOMERORDER.CUSTOMERORDERID);
        public static final UniqueKey<CustomerorderdetailRecord> KEY_CUSTOMERORDERDETAIL_PRIMARY = Internal.createUniqueKey(Customerorderdetail.CUSTOMERORDERDETAIL, "KEY_customerorderdetail_PRIMARY", Customerorderdetail.CUSTOMERORDERDETAIL.CUSTOMERORDERDETAILID);
        public static final UniqueKey<DealerRecord> KEY_DEALER_PRIMARY = Internal.createUniqueKey(Dealer.DEALER, "KEY_dealer_PRIMARY", Dealer.DEALER.DEALERID);
        public static final UniqueKey<DealerRecord> KEY_DEALER_DEALER_COMPANY_UNIQUE = Internal.createUniqueKey(Dealer.DEALER, "KEY_dealer_dealer_company_unique", Dealer.DEALER.COMPANYNAME);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, "KEY_product_PRIMARY", Product.PRODUCT.PRODUCTID);
        public static final UniqueKey<ProductcategoryRecord> KEY_PRODUCTCATEGORY_PRIMARY = Internal.createUniqueKey(Productcategory.PRODUCTCATEGORY, "KEY_productcategory_PRIMARY", Productcategory.PRODUCTCATEGORY.CATEGORYID);
        public static final UniqueKey<ProductcategoryRecord> KEY_PRODUCTCATEGORY_PRODUCTCATEGORY_NAME_UNIQUE = Internal.createUniqueKey(Productcategory.PRODUCTCATEGORY, "KEY_productcategory_productCategory_name_unique", Productcategory.PRODUCTCATEGORY.CATEGORYNAME);
        public static final UniqueKey<PurchaseRecord> KEY_PURCHASE_PRIMARY = Internal.createUniqueKey(Purchase.PURCHASE, "KEY_purchase_PRIMARY", Purchase.PURCHASE.PURCHASEID);
        public static final UniqueKey<PurchaseRecord> KEY_PURCHASE_PURCHASE_PURCHASENAME_UNIQUE = Internal.createUniqueKey(Purchase.PURCHASE, "KEY_purchase_purchase_purchaseName_unique", Purchase.PURCHASE.PURCHASENAME);
        public static final UniqueKey<PurchasedetailRecord> KEY_PURCHASEDETAIL_PRIMARY = Internal.createUniqueKey(Purchasedetail.PURCHASEDETAIL, "KEY_purchasedetail_PRIMARY", Purchasedetail.PURCHASEDETAIL.PURCHASEDETAILID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.USERID);
        public static final UniqueKey<UsertypeRecord> KEY_USERTYPE_PRIMARY = Internal.createUniqueKey(Usertype.USERTYPE, "KEY_usertype_PRIMARY", Usertype.USERTYPE.USERTYPEID);
        public static final UniqueKey<UsertypeRecord> KEY_USERTYPE_USERTYPE_NAME_UNIQUE = Internal.createUniqueKey(Usertype.USERTYPE, "KEY_usertype_userType_name_unique", Usertype.USERTYPE.USERTYPENAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CustomerRecord, UserRecord> CUSTOMER_USERID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_USER_PRIMARY, Customer.CUSTOMER, "customer_userId_fk", Customer.CUSTOMER.USERID);
        public static final ForeignKey<CustomerorderRecord, CustomerRecord> ORDER_CUSTOMERID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_CUSTOMER_PRIMARY, Customerorder.CUSTOMERORDER, "order_customerId_fk", Customerorder.CUSTOMERORDER.CUSTOMERID);
        public static final ForeignKey<CustomerorderdetailRecord, ProductRecord> CUSTOMERORDERDETAIL_PRODUCTID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_PRODUCT_PRIMARY, Customerorderdetail.CUSTOMERORDERDETAIL, "customerOrderDetail_productId_fk", Customerorderdetail.CUSTOMERORDERDETAIL.PRODUCTID);
        public static final ForeignKey<CustomerorderdetailRecord, CustomerorderRecord> CUSTOMERORDERDETAIL_CUSTOMERORDERID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_CUSTOMERORDER_PRIMARY, Customerorderdetail.CUSTOMERORDERDETAIL, "customerOrderDetail_customerOrderId_fk", Customerorderdetail.CUSTOMERORDERDETAIL.CUSTOMERORDERID);
        public static final ForeignKey<DealerRecord, UserRecord> DEALER_USERID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_USER_PRIMARY, Dealer.DEALER, "dealer_userId_fk", Dealer.DEALER.USERID);
        public static final ForeignKey<ProductRecord, ProductcategoryRecord> PRODUCT_CATEGORYID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_PRODUCTCATEGORY_PRIMARY, Product.PRODUCT, "product_categoryId_fk", Product.PRODUCT.CATEGORYID);
        public static final ForeignKey<ProductRecord, BrandRecord> PRODUCT_BRANDID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_BRAND_PRIMARY, Product.PRODUCT, "product_brandId_fk", Product.PRODUCT.BRANDID);
        public static final ForeignKey<ProductRecord, DealerRecord> PRODUCT_DEALERID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_DEALER_PRIMARY, Product.PRODUCT, "product_dealerId_fk", Product.PRODUCT.DEALERID);
        public static final ForeignKey<PurchasedetailRecord, PurchaseRecord> PURCHASEDETAIL_PURCHASEID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_PURCHASE_PRIMARY, Purchasedetail.PURCHASEDETAIL, "purchaseDetail_purchaseId_fk", Purchasedetail.PURCHASEDETAIL.PURCHASEID);
        public static final ForeignKey<PurchasedetailRecord, ProductRecord> PRODUCT_PRODUCTID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_PRODUCT_PRIMARY, Purchasedetail.PURCHASEDETAIL, "product_productId_fk", Purchasedetail.PURCHASEDETAIL.PRODUCTID);
        public static final ForeignKey<UserRecord, UsertypeRecord> USER_USERTYPEID_FK = Internal.createForeignKey(com.ims.dataAccess.Keys.KEY_USERTYPE_PRIMARY, User.USER, "user_userTypeId_fk", User.USER.USERTYPEID);
    }
}
