/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess;


import com.ims.dataAccess.tables.Brand;
import com.ims.dataAccess.tables.Customer;
import com.ims.dataAccess.tables.Customerorder;
import com.ims.dataAccess.tables.Customerorderdetail;
import com.ims.dataAccess.tables.Dealer;
import com.ims.dataAccess.tables.Product;
import com.ims.dataAccess.tables.Productcategory;
import com.ims.dataAccess.tables.Purchase;
import com.ims.dataAccess.tables.Purchasedetail;
import com.ims.dataAccess.tables.User;
import com.ims.dataAccess.tables.Usertype;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in inventorymanagement
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>inventorymanagement.brand</code>.
     */
    public static final Brand BRAND = Brand.BRAND;

    /**
     * The table <code>inventorymanagement.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>inventorymanagement.customerorder</code>.
     */
    public static final Customerorder CUSTOMERORDER = Customerorder.CUSTOMERORDER;

    /**
     * The table <code>inventorymanagement.customerorderdetail</code>.
     */
    public static final Customerorderdetail CUSTOMERORDERDETAIL = Customerorderdetail.CUSTOMERORDERDETAIL;

    /**
     * The table <code>inventorymanagement.dealer</code>.
     */
    public static final Dealer DEALER = Dealer.DEALER;

    /**
     * The table <code>inventorymanagement.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>inventorymanagement.productcategory</code>.
     */
    public static final Productcategory PRODUCTCATEGORY = Productcategory.PRODUCTCATEGORY;

    /**
     * The table <code>inventorymanagement.purchase</code>.
     */
    public static final Purchase PURCHASE = Purchase.PURCHASE;

    /**
     * The table <code>inventorymanagement.purchasedetail</code>.
     */
    public static final Purchasedetail PURCHASEDETAIL = Purchasedetail.PURCHASEDETAIL;

    /**
     * The table <code>inventorymanagement.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>inventorymanagement.usertype</code>.
     */
    public static final Usertype USERTYPE = Usertype.USERTYPE;
}
