/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Common;

import customcontrols.ActionBar;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Vidhya Mohan
 */
public class BaseNavigationFrame extends MainFrame {

    public ActionBar actionBar;
    public JPanel topPane;
    public JPanel centerPane;
    public JPanel bottomPane;
    public JPanel leftPane;
    
    public JPanel sideNavigation;
    
    /**
     * Creates new form BaseNavigationFrame
     */
    public BaseNavigationFrame() {
        initComponents();
        setPanes();
        
    }
    
    public void setPanes() {
        setLayout(new BorderLayout());
        topPane = new JPanel();
        topPane.setLayout(new BoxLayout(topPane, BoxLayout.Y_AXIS));
        topPane.setBorder(new EmptyBorder(0,0,0,0));
        add(topPane, BorderLayout.NORTH);
        
        centerPane = new JPanel();
        //centerPane.setLayout(new BoxLayout(centerPane, BoxLayout.PAGE_AXIS));
        centerPane.setBorder(new EmptyBorder(40, 15,15,0));
        add(centerPane, BorderLayout.CENTER);
        
        bottomPane = new JPanel();
        bottomPane.setLayout(new BoxLayout(bottomPane, BoxLayout.Y_AXIS));
        bottomPane.setBorder(new EmptyBorder(0,0,0,0));
        add(bottomPane, BorderLayout.SOUTH);
        
        leftPane = new JPanel();        
        leftPane.setLayout(new BoxLayout(leftPane, BoxLayout.Y_AXIS));
        add(leftPane, BorderLayout.WEST);        
    }
    
    public void setNavigation() {
        
        actionBar = new ActionBar();
        topPane.add(actionBar);        
        
        sideNavigation = new JPanel();
        sideNavigation.setPreferredSize(new Dimension(300,100));
        sideNavigation.setBackground(skin.slateBlackColor);
        
        leftPane.add(sideNavigation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
