/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Common;

import customcontrols.ActionBar;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Vidhya Mohan
 */
public class TestFrame extends MainFrame {

    JPanel navBar;
    ActionBar actionBar;
    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        super();
        initComponents();
        this.setSize(new Dimension(1200, 1000));
        Initialize();
    }
    
    public void Initialize() {
      
       JPanel pnlBox = new JPanel();
       this.setLayout(new GridBagLayout());    
       
       GridBagConstraints gbc = new GridBagConstraints();
       gbc.anchor = GridBagConstraints.FIRST_LINE_START;
       JPanel panel1 = new JPanel();
       panel1.setBackground(skin.bloodRedColor);
       panel1.setPreferredSize(new Dimension(800,50));
       gbc.fill  = GridBagConstraints.VERTICAL;
       gbc.anchor = GridBagConstraints.NORTHWEST;
     
       gbc.gridx = 0;
       gbc.gridy = 0;
       gbc.fill = 1;
       gbc.insets = new Insets(2,3,4,5); 
       this.add(panel1, gbc);
       
       JPanel panel2 = new JPanel();
       panel2.setBackground(skin.darkBlueColor);
       panel2.setPreferredSize(new Dimension(800,50));
       gbc.gridx = 0; 
       gbc.gridy = 1;
       gbc.fill = 1;
       this.add(panel2, gbc);
       
       JPanel panel3 = new JPanel();
       panel3.setBackground(skin.darkBlueColor);
       panel3.setPreferredSize(new Dimension(800,50));
       gbc.gridx = 0;
       gbc.gridy = 2;
       gbc.fill = 3;
       this.add(panel3, gbc);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
