/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Common;

import Enums.ActionBarActions;
import EventObject.TabChangeEventObj;
import Presentation.Product.BrowseProduct;
import Presentation.Product.ProductDetail;
import Presentation.Product.ProductFilterPanel;
import customcontrols.Panel;

import java.awt.Color;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Vidhya Mohan
 */
public class TabNavigationFrame extends BaseNavigationFrame {

    protected JTabbedPane tabControl;
    protected Panel pnlBrowse;
    protected Panel pnlDetail;    
    /**
     * Creates new form TabNavigationFrame
     */
    public TabNavigationFrame() {
        super();
        initComponents();
        this.setBackground(this.skin.frameBackgroundColor);       
        this.setSize(this.skin.frameDimension);   
        initializeBaseNavigationFrame();
        initializeTabNavigationFrame();
        tabControl.addChangeListener(e -> TabChangeListener(e));
    }
    
    public void useMigLayout() {      
        this.pnlBrowse.setLayout(new MigLayout());
        this.pnlDetail.setLayout(new MigLayout());
    }
    
    public void initializeTabNavigationFrame() {
        centerPane.setLayout(new MigLayout());
        
        pnlBrowse = new Panel();        
        pnlBrowse.setLayout(new BoxLayout(pnlBrowse, BoxLayout.PAGE_AXIS)); 
        
        pnlDetail = new Panel();          
        pnlDetail.setLayout(new BoxLayout(pnlDetail, BoxLayout.PAGE_AXIS)); 
        
        tabControl = new JTabbedPane();   
        tabControl.setFont(skin.font24);
        tabControl.addTab("Browse", pnlBrowse);
        tabControl.addTab("Detail", pnlDetail);       
        
       // actionBar.addClickedListener( e -> { ActionItemClickedHandlers(e); });

        centerPane.add(tabControl);
        
    }    
  
    protected void changeTab(TabChangeEventObj eventObj) {
      
    }
    
    protected void TabChangeListener(ChangeEvent e) {
              
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
