/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.records;


import com.ims.dataAccess.tables.Brand;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrandRecord extends UpdatableRecordImpl<BrandRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 601411176;

    /**
     * Setter for <code>inventorymanagement.brand.brandId</code>.
     */
    public void setBrandid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inventorymanagement.brand.brandId</code>.
     */
    public Integer getBrandid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inventorymanagement.brand.brandName</code>.
     */
    public void setBrandname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inventorymanagement.brand.brandName</code>.
     */
    public String getBrandname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>inventorymanagement.brand.brandDescription</code>.
     */
    public void setBranddescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>inventorymanagement.brand.brandDescription</code>.
     */
    public String getBranddescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Brand.BRAND.BRANDID;
    }

    @Override
    public Field<String> field2() {
        return Brand.BRAND.BRANDNAME;
    }

    @Override
    public Field<String> field3() {
        return Brand.BRAND.BRANDDESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getBrandid();
    }

    @Override
    public String component2() {
        return getBrandname();
    }

    @Override
    public String component3() {
        return getBranddescription();
    }

    @Override
    public Integer value1() {
        return getBrandid();
    }

    @Override
    public String value2() {
        return getBrandname();
    }

    @Override
    public String value3() {
        return getBranddescription();
    }

    @Override
    public BrandRecord value1(Integer value) {
        setBrandid(value);
        return this;
    }

    @Override
    public BrandRecord value2(String value) {
        setBrandname(value);
        return this;
    }

    @Override
    public BrandRecord value3(String value) {
        setBranddescription(value);
        return this;
    }

    @Override
    public BrandRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BrandRecord
     */
    public BrandRecord() {
        super(Brand.BRAND);
    }

    /**
     * Create a detached, initialised BrandRecord
     */
    public BrandRecord(Integer brandid, String brandname, String branddescription) {
        super(Brand.BRAND);

        set(0, brandid);
        set(1, brandname);
        set(2, branddescription);
    }
}
