/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.records;


import com.ims.dataAccess.tables.Product;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record9<Integer, String, Integer, String, Long, byte[], Integer, Integer, Integer> {

    private static final long serialVersionUID = -850003744;

    /**
     * Setter for <code>inventorymanagement.product.productId</code>.
     */
    public void setProductid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.productId</code>.
     */
    public Integer getProductid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inventorymanagement.product.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>inventorymanagement.product.availableStock</code>.
     */
    public void setAvailablestock(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.availableStock</code>.
     */
    public Integer getAvailablestock() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inventorymanagement.product.productDescription</code>.
     */
    public void setProductdescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.productDescription</code>.
     */
    public String getProductdescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>inventorymanagement.product.price</code>.
     */
    public void setPrice(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.price</code>.
     */
    public Long getPrice() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>inventorymanagement.product.image</code>.
     */
    public void setImage(byte... value) {
        set(5, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.image</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>inventorymanagement.product.categoryId</code>.
     */
    public void setCategoryid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.categoryId</code>.
     */
    public Integer getCategoryid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>inventorymanagement.product.brandId</code>.
     */
    public void setBrandid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.brandId</code>.
     */
    public Integer getBrandid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>inventorymanagement.product.dealerId</code>.
     */
    public void setDealerid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>inventorymanagement.product.dealerId</code>.
     */
    public Integer getDealerid() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Integer, String, Long, byte[], Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, Integer, String, Long, byte[], Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.PRODUCTID;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Product.PRODUCT.AVAILABLESTOCK;
    }

    @Override
    public Field<String> field4() {
        return Product.PRODUCT.PRODUCTDESCRIPTION;
    }

    @Override
    public Field<Long> field5() {
        return Product.PRODUCT.PRICE;
    }

    @Override
    public Field<byte[]> field6() {
        return Product.PRODUCT.IMAGE;
    }

    @Override
    public Field<Integer> field7() {
        return Product.PRODUCT.CATEGORYID;
    }

    @Override
    public Field<Integer> field8() {
        return Product.PRODUCT.BRANDID;
    }

    @Override
    public Field<Integer> field9() {
        return Product.PRODUCT.DEALERID;
    }

    @Override
    public Integer component1() {
        return getProductid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAvailablestock();
    }

    @Override
    public String component4() {
        return getProductdescription();
    }

    @Override
    public Long component5() {
        return getPrice();
    }

    @Override
    public byte[] component6() {
        return getImage();
    }

    @Override
    public Integer component7() {
        return getCategoryid();
    }

    @Override
    public Integer component8() {
        return getBrandid();
    }

    @Override
    public Integer component9() {
        return getDealerid();
    }

    @Override
    public Integer value1() {
        return getProductid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAvailablestock();
    }

    @Override
    public String value4() {
        return getProductdescription();
    }

    @Override
    public Long value5() {
        return getPrice();
    }

    @Override
    public byte[] value6() {
        return getImage();
    }

    @Override
    public Integer value7() {
        return getCategoryid();
    }

    @Override
    public Integer value8() {
        return getBrandid();
    }

    @Override
    public Integer value9() {
        return getDealerid();
    }

    @Override
    public ProductRecord value1(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductRecord value3(Integer value) {
        setAvailablestock(value);
        return this;
    }

    @Override
    public ProductRecord value4(String value) {
        setProductdescription(value);
        return this;
    }

    @Override
    public ProductRecord value5(Long value) {
        setPrice(value);
        return this;
    }

    @Override
    public ProductRecord value6(byte... value) {
        setImage(value);
        return this;
    }

    @Override
    public ProductRecord value7(Integer value) {
        setCategoryid(value);
        return this;
    }

    @Override
    public ProductRecord value8(Integer value) {
        setBrandid(value);
        return this;
    }

    @Override
    public ProductRecord value9(Integer value) {
        setDealerid(value);
        return this;
    }

    @Override
    public ProductRecord values(Integer value1, String value2, Integer value3, String value4, Long value5, byte[] value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer productid, String name, Integer availablestock, String productdescription, Long price, byte[] image, Integer categoryid, Integer brandid, Integer dealerid) {
        super(Product.PRODUCT);

        set(0, productid);
        set(1, name);
        set(2, availablestock);
        set(3, productdescription);
        set(4, price);
        set(5, image);
        set(6, categoryid);
        set(7, brandid);
        set(8, dealerid);
    }
}
