/*
 * This file is generated by jOOQ.
 */
package com.ims.dataAccess.tables.records;


import com.ims.dataAccess.tables.Purchasedetail;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchasedetailRecord extends UpdatableRecordImpl<PurchasedetailRecord> implements Record5<Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = -815504605;

    /**
     * Setter for <code>inventorymanagement.purchasedetail.purchaseDetailId</code>.
     */
    public void setPurchasedetailid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inventorymanagement.purchasedetail.purchaseDetailId</code>.
     */
    public Integer getPurchasedetailid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inventorymanagement.purchasedetail.purchaseId</code>.
     */
    public void setPurchaseid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inventorymanagement.purchasedetail.purchaseId</code>.
     */
    public Integer getPurchaseid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inventorymanagement.purchasedetail.productId</code>.
     */
    public void setProductid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inventorymanagement.purchasedetail.productId</code>.
     */
    public Integer getProductid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inventorymanagement.purchasedetail.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>inventorymanagement.purchasedetail.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>inventorymanagement.purchasedetail.purchaseNotes</code>.
     */
    public void setPurchasenotes(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>inventorymanagement.purchasedetail.purchaseNotes</code>.
     */
    public String getPurchasenotes() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Purchasedetail.PURCHASEDETAIL.PURCHASEDETAILID;
    }

    @Override
    public Field<Integer> field2() {
        return Purchasedetail.PURCHASEDETAIL.PURCHASEID;
    }

    @Override
    public Field<Integer> field3() {
        return Purchasedetail.PURCHASEDETAIL.PRODUCTID;
    }

    @Override
    public Field<Integer> field4() {
        return Purchasedetail.PURCHASEDETAIL.QUANTITY;
    }

    @Override
    public Field<String> field5() {
        return Purchasedetail.PURCHASEDETAIL.PURCHASENOTES;
    }

    @Override
    public Integer component1() {
        return getPurchasedetailid();
    }

    @Override
    public Integer component2() {
        return getPurchaseid();
    }

    @Override
    public Integer component3() {
        return getProductid();
    }

    @Override
    public Integer component4() {
        return getQuantity();
    }

    @Override
    public String component5() {
        return getPurchasenotes();
    }

    @Override
    public Integer value1() {
        return getPurchasedetailid();
    }

    @Override
    public Integer value2() {
        return getPurchaseid();
    }

    @Override
    public Integer value3() {
        return getProductid();
    }

    @Override
    public Integer value4() {
        return getQuantity();
    }

    @Override
    public String value5() {
        return getPurchasenotes();
    }

    @Override
    public PurchasedetailRecord value1(Integer value) {
        setPurchasedetailid(value);
        return this;
    }

    @Override
    public PurchasedetailRecord value2(Integer value) {
        setPurchaseid(value);
        return this;
    }

    @Override
    public PurchasedetailRecord value3(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public PurchasedetailRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public PurchasedetailRecord value5(String value) {
        setPurchasenotes(value);
        return this;
    }

    @Override
    public PurchasedetailRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchasedetailRecord
     */
    public PurchasedetailRecord() {
        super(Purchasedetail.PURCHASEDETAIL);
    }

    /**
     * Create a detached, initialised PurchasedetailRecord
     */
    public PurchasedetailRecord(Integer purchasedetailid, Integer purchaseid, Integer productid, Integer quantity, String purchasenotes) {
        super(Purchasedetail.PURCHASEDETAIL);

        set(0, purchasedetailid);
        set(1, purchaseid);
        set(2, productid);
        set(3, quantity);
        set(4, purchasenotes);
    }
}
