/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Presentation.Common.MainFrame;
import Presentation.Product.ProductNavigation;
import customcontrols.Label;
import customcontrols.LabelTextField;
import customcontrols.Panel;
import customcontrols.PictureBox;
import java.awt.Image;


/**
 *
 * @author Vidhya Mohan
 */
public class LoginOld extends MainFrame {

    private PictureBox picBoxLogin;
    private LabelTextField lblTextPassword;
    private LabelTextField lblTextUserName;
    private Label lblInventoryManagement;
    private Label lblLoginLabel;
    

    
    public LoginOld() {        
        this.setBackground(this.skin.frameBackgroundColor); 
        pnlLeft = new Panel();
        picBoxLogin = new PictureBox();
        lblLoginLabel = new Label();
        lblTextUserName = new LabelTextField();
        lblTextPassword = new LabelTextField();
        lblInventoryManagement = new Label();
        
        this.lblLoginLabel.setForeground(this.skin.blueGreenColor);
        this.lblLoginLabel.setFont(skin.fontBold20);
        this.lblTextUserName.setLabelText("User Name: ");
        this.lblTextPassword.setLabelText("Password: ");
        this.lblInventoryManagement.setForeground(this.skin.milkWhiteColor);
         this.lblInventoryManagement.setFont(skin.fontBold18);
        this.pnlLeft.setBackground(getSkin().skyBlueColor);
        
         this.pnlLeft.add(lblLoginLabel);
         this.pnlLeft.add(lblTextUserName);
         this.pnlLeft.add(lblTextPassword);
         this.pnlLeft.add(lblInventoryManagement);
         
        
        Image img = getImageByPath("/Resources/Images/login.png");
        
        this.picBoxLogin.setPicture(img);     
        this.picBoxLogin.setImageForeColor(this.skin.milkWhiteColor);
        
        this.add(picBoxLogin);
        this.add(pnlLeft);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //DashBoard dash = new DashBoard();
        //dash.setVisible(true);
        ProductNavigation pNav = new ProductNavigation();
        pNav.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables
}
