/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customcontrols;

import Helper.UIHelper;
import Skin.Skin;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Vidhya Mohan
 */
public class Panel extends javax.swing.JPanel {

    protected Skin skin = new Skin();
    protected UIHelper uiHelper = new UIHelper();
    
    public Panel() {       
        this.setLayout(null);
    }
    
    public void setTitle(String title) {
        TitledBorder border = BorderFactory.createTitledBorder(title);
        border.setTitleFont(skin.font22);     
        border.setTitleColor(skin.lightSteelBlueColor);
        border.setBorder(BorderFactory.createLineBorder(skin.lightSteelBlueColor, 2));
        this.setBorder(border);
    }
    
    protected Image getImageByPath(String path) {
        Image imgIcon = new ImageIcon(this.getClass().getResource(path)).getImage();
        return imgIcon;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
